### ISSUE TITLE
TrrntZipUI: Add support for compression level

### ISSUE THREAD

**Issue by roger-** [RomVault/RVWorld#15]
I'd like to use the maximum compression level for 7zip, but apparently that's not the default and I don't see a way to configure it.

**Comment by gjefferyes** [comment]
7zip compression in RV & TrrntZip is high, (as high as is used by t7z)
The goal is also to standardize rv7z so that all files match like zip trrntzip, and so changing the compression parameters would not produce a consistent archive.
