### ISSUE TITLE
Compute CRC of Zip files

### ISSUE THREAD

**Issue by wally666** [RomVault/RVWorld#2]
First of all: GREAT WORK!

Have you considered read already computed CRC of Zip files content directly from archive instead of processing stream? Some ROM collections is impossible to Fix in a rational amout of time :(

using (System.IO.Stream stream = System.IO.File.OpenRead(FILEPATHNAME))
using (var archive = SharpCompress.Archives.ArchiveFactory.Open(stream))
{
                            foreach (var entry in archive.Entries.Where(a => !a.IsDirectory))
                            {
                                    Crc = entry.Crc.ToString("X2");
                                    Size = entry.Size;
                            }
}

**Comment by gjefferyes** [comment]
You can already do this in the options, set scan to level 1 and it only reads the CRC from the headers and assumes the ZIP is good.
