### ISSUE TITLE
Fixes for Linux were reverted

### ISSUE THREAD

**Issue by dbermond** [RomVault/RVWorld#3]
The fixes for Linux (pull request #1) were reverted on git master.

The pull request #1 was merged in commit 00925e9eec59be6163094dc5e2a6b72f963e36ad. But these changes were completely reverted in commits d65bbef2cfa570db0008c0346b5c8522754ea375 and 9c18c4107d11f508e622e1ddf4de745411c36723.

Can these changes be implemented again? TorrentZip does not build on Linux without these fixes (and some others), and also produces wrong filenames on Linux as described in the pull request discussion.

**Comment by gjefferyes** [comment]
I re-applied this fixes.
